"""empty message

Revision ID: 8ee0c81392da
Revises: e7a96783ad99
Create Date: 2024-02-05 19:13:45.376140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee0c81392da'
down_revision = 'e7a96783ad99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('climate', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('terrain', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('rotation', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('population', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('orbital_period', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('diameter', sa.String(length=250), nullable=False))
        batch_op.drop_column('diametro')
        batch_op.drop_column('periodo_orbital')
        batch_op.drop_column('rotación')
        batch_op.drop_column('clima')
        batch_op.drop_column('población')
        batch_op.drop_column('nombre')
        batch_op.drop_column('terreno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terreno', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('población', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('clima', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rotación', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('periodo_orbital', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('diametro', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_column('diameter')
        batch_op.drop_column('orbital_period')
        batch_op.drop_column('population')
        batch_op.drop_column('rotation')
        batch_op.drop_column('terrain')
        batch_op.drop_column('climate')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
