"""empty message

Revision ID: e7a96783ad99
Revises: eb091a3f5c35
Create Date: 2024-02-02 19:47:38.248641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a96783ad99'
down_revision = 'eb091a3f5c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('clima', sa.String(length=50), nullable=False),
    sa.Column('terreno', sa.String(length=250), nullable=False),
    sa.Column('rotación', sa.String(length=250), nullable=False),
    sa.Column('población', sa.String(length=250), nullable=False),
    sa.Column('periodo_orbital', sa.String(length=250), nullable=False),
    sa.Column('diametro', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_Vehicles', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_planets', sa.Integer(), nullable=True),
    sa.Column('id_vehicles', sa.Integer(), nullable=True),
    sa.Column('id_person', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_person'], ['person.id'], ),
    sa.ForeignKeyConstraint(['id_planets'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_vehicles'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_personaje', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('edad', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('genero', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('color_ojos', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('color_cabello', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('altura', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['nombre_personaje'])
        batch_op.drop_column('name')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['nombre'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nombre')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('altura')
        batch_op.drop_column('color_cabello')
        batch_op.drop_column('color_ojos')
        batch_op.drop_column('genero')
        batch_op.drop_column('edad')
        batch_op.drop_column('nombre_personaje')

    op.drop_table('favorites')
    op.drop_table('vehicles')
    op.drop_table('planets')
    # ### end Alembic commands ###
